server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost/easy-notes
      port: 27017

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass123


## Mybatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml

jwt:
  secret: ji934fsfS9fA01eoPq23
  expiration: 3600000
  header: JWTHeaderName

oauth2:
  clients:
    github:
      client-id: d2456e0d3f62d5838fb2
      client-name: Github
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user
    qq:
      client-id: d2456e0d3f62d5838fb2
      client-name: QQ
      client-secret: 60ec6d3c4dcf47281fe06124da535faf33cb17ec
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      user-info-uri: https://api.github.com/user
