server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: pass

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass123


## Mybatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml

jwt:
  header: 123
  tokenHead: fd2